alias: "Saugroboter bei Abwesenheit"
description: "Startet den Saugroboter automatisch, wenn unter der Woche niemand zuhause ist"
trigger:
  - platform: time
    at: "09:00:00"
  - platform: state
    entity_id: group.family
    to: "not_home"
    for: "00:30:00"
condition:
  - condition: state
    entity_id: group.family
    state: "not_home"
  - condition: time
    after: "08:00:00"
    before: "12:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: vacuum.saugroboter
    state: "docked"
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: vacuum.saugroboter
            attribute: battery_level
            above: 40
        sequence:
          - service: vacuum.start
            target:
              entity_id: vacuum.saugroboter
          - service: notify.mobile_app
            data:
              message: "Saugroboter gestartet"
      - conditions:
          - condition: numeric_state
            entity_id: vacuum.saugroboter
            attribute: battery_level
            below: 40
        sequence:
          - service: notify.mobile_app
            data:
              message: "Saugroboter Batterie zu niedrig"
  - service: logbook.log
    data:
      name: Haushalt
      message: "Saugroboter Routine ausgefuehrt"
